---
- include: clean.yml
- name: 创建 Hadoop 目录
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{HADOOP_LOGS}}"
    - "{{HADOOP_DATANODE_DIR}}"
    - "{{HADOOP_NAMENODE_DIR}}"
    - "{{HADOOP_TMP_DIR}}"


- name: 下载 Hadoop
  unarchive:
    creates: "{{HADOOP_HOME}}"
    src: "hadoop-2.7.3.tar.gz"
    dest: "{{ROOT}}"
    owner: root
    group: root
    mode: 0755

- name: 生成 Hadoop 配置文件
  template:
    src: "{{item}}"
    dest: "{{HADOOP_HOME}}/etc/hadoop/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "core-site.xml"
    - "hdfs-site.xml"
    - "hadoop-env.sh"
    - "slaves"

- include: namenode.yml
  when: "'namenode' in group_names"
- include: datanode.yml
  when: "'datanode' in group_names"


- name: 添加 Bash 的 Hadoop Prefix 环境变量
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: ^export\sHADOOP_PREFIX=
    line: "export HADOOP_PREFIX={{HADOOP_HOME}}"
    insertbefore: ^export\sJAVA_HOME=

- name: 尝试上传本地的 Hosts 文件到 HDFS
  command: "{{HADOOP_HOME}}/bin/hdfs dfs -put /etc/hosts /hosts-{{ansible_default_ipv4.address}}"

