---
- hosts: presto-2
  tasks:
    - include: "./experiments/events.yml"
      vars:
        - count: "{{item}}"
      with_items:
        - 5
        - 10
        - 100
        - 1000
        - 10000
        - 100000
        - 1000000
        - 5000000
        - 10000000