---
- hosts: all
  gather_facts: no
  tasks:
    - name: "获取运行状态"
      raw: "vboxmanage showvminfo {{inventory_hostname}} --machinereadable | grep VMState="
      delegate_to: 127.0.0.1
      register: "vmstate"

    - name: "关闭电源"
      delegate_to: 127.0.0.1
      command: "vboxmanage controlvm {{inventory_hostname}} poweroff"
      when: "'runnin' in vmstate.stdout"

    - name: "还原到 {{DEFAULT_VM_SNAPSHOT}} 镜像"
      delegate_to: 127.0.0.1
      command: "vboxmanage snapshot {{inventory_hostname}} restore {{DEFAULT_VM_SNAPSHOT}}"

    - name: "启动电源"
      delegate_to: 127.0.0.1
      command: "vboxmanage startvm {{inventory_hostname}} --type=headless"

    - name: "等待启动完成"
      wait_for:
        delay: 5
        host: "{{ inventory_hostname }}"
        port: 22
      delegate_to: 127.0.0.1

    - name: "显示消息"
      delegate_to: 127.0.0.1
      run_once: yes
      ignore_errors: yes
      command: "notify-send -i dialog-warning 'Ansible' '重置完成'"