---
- hosts: all
  roles:
    - base
    - supervisord
    - jdk

- hosts: namenode,datanode
  roles:
    - hadoop

- hosts: mysql
  roles:
    - mysql

- hosts: hive
  roles:
    - {
      role: hive,
      mysql_host: "{{ (hostvars[groups['mysql']|first]).lan_ip }}:{{ MYSQL_PORT }}"
    }

- hosts: presto
  roles:
    - {
      role: presto,
      hivemetastore_host:  "{{ (hostvars[groups['hive']|first]).lan_ip }}:{{ HIVE_METASTORE_PORT }}"
    }

- hosts: zeppelin
  roles:
    - zeppelin
