---
- name: 下载 JDK
  unarchive:
    creates: "{{JAVA_HOME}}"
    src: "jdk-8u131-linux-x64.tar.gz"
    dest: "{{ROOT}}"
    owner: root
    group: root
    mode: 0755

- name: 下载 Jokia
  copy:
    src: "jolokia-jvm-1.3.7-agent.jar"
    dest: "{{JOLOKIA_FILE}}"
    owner: root
    group: root
    mode: 0755

- name: 添加 Bash 的 JAVA_HOME 环境变量
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: ^export\sJAVA_HOME=
    line: "export JAVA_HOME={{JAVA_HOME}}"

- name: 添加 Java 工具到 Path 路径
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: ^export\sPATH=\$JAVA_HOME\/bin:\$PATH
    line: export PATH=$JAVA_HOME/bin:$PATH
    insertafter: ^export\sJAVA_HOME=