---
- include: install.yml

- file:
    path: "/var/log/telegraf/telegraf.log"
    owner: telegraf
    group: telegraf
    state: touch

- name: 生成 telegraf 配置文件
  template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: 0644
    validate: telegraf --test --config %s

- name: 重启 Telegraf
  service:
    name: telegraf
    state: restarted